version: '3.9'

services:

  database:
    container_name: dizi-izi-database
    image: postgres:15-alpine
    volumes:
      - dizi_postgres_dev:/var/lib/postgresql/data/
    env_file:
      - .env
    restart: always
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin" ]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    container_name: dizi-izi-backend
    image: diziizi/dizi-izi-backend:latest
    build: .
    restart: always
    ports:
      - "80:8000"
    env_file:
      - .env
    depends_on:
      - database
#    uncomment for develop mode
#    volumes:
#      - ./:/app

volumes:
  dizi_postgres_dev:
