version: '3.9'

services:

  database:
    container_name: dizi-izi-database
    image: postgres:15-alpine
    volumes:
      - dizi_izi_postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    container_name: dizi-izi-backend
    image: diziizi/dizi-izi-backend
    restart: always
    volumes:
      - static:/app/static/
      - media:/app/media/
    env_file:
      - .env
    depends_on:
      - database

  frontend:
    container_name: dizi-izi-frontend
    image: diziizi/dizi-izi-frontend
    volumes:
      - frontend:/app/
    depends_on:
      - backend

  nginx:
    image: nginx:1.24-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static:/var/html/static/
      - media:/var/html/media/
      - frontend:/usr/share/nginx/html/
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    depends_on:
      - backend
      - frontend
    restart: unless-stopped
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot:v2.9.0
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    depends_on:
      - nginx
    restart: unless-stopped
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
  static:
  media:
  frontend:
  dizi_izi_postgres_data:
    external: true
