name: Check
on:
  workflow_dispatch:
  push:
  pull_request:
    branches:
      - main
      - develop

jobs:
  flake8:
    name: Running flake8 check for code
    runs-on: ubuntu-22.04
    steps:
      - name: Flake8 Code Check
        uses: dizi-izi-plan/dizi-izi-backend/.github/actions/flake8@ci-cd-pipelines
