name: Check
on:
  workflow_dispatch:
  push:
  pull_request:
    branches:
      - main
      - develop

jobs:
  flake8:
    name: Running flake8 check for code
    runs-on: ubuntu-22.04
    steps:
      - name: Repository checkout
        uses: actions/checkout@v4

      - name: Check Python version
        run: python --version

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pep8-naming flake8-broken-line flake8-return flake8-isort
          pip install -r requirements.txt

      - name: Testing with flake8
        run: python -m flake8

  flake8_t:
    name: Running flake8 check for code
    runs-on: ubuntu-22.04
    steps:

      - name: Repository checkout
        uses: actions/checkout@v4

      - name: Flake8 Code Check
        uses: ./.github/actions/flake8@ci-cd-pipelines
