name: Deploy to server
on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to server
    runs-on: ubuntu-22.04
    steps:

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            cd /home/www/infra
            
            ./restart.sh all
