name: Deploy to server
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop

jobs:
  flake8:
    uses: dizi-izi-plan/dizi-izi-backend/.github/workflows/check.yml@ci-cd-pipelines

  docker:
    needs: flake8
    uses: dizi-izi-plan/dizi-izi-backend/.github/workflows/docker.yml@ci-cd-pipelines
    with:
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}

  server:
    needs: docker
    uses: dizi-izi-plan/dizi-izi-backend/.github/workflows/server_refresh.yml@ci-cd-pipelines
    with:
      server_host: ${{ secrets.SERVER_HOST }}
      server_username: ${{ secrets.SERVER_USERNAME }}
      server_ssh_key: ${{ secrets.SSH_KEY }}
      server_passphrase: ${{ secrets.SSH_PASSPHRASE }}

