name: Deploy to server
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop

jobs:
  flake8:
    name: Tests
    uses: dizi-izi-plan/dizi-izi-backend/.github/workflows/check.yml@ci-cd-pipelines

  docker:
    name: Docker
    needs: flake8
    uses: dizi-izi-plan/dizi-izi-backend/.github/workflows/docker.yml@ci-cd-pipelines
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  server:
    name: Server
    needs: docker
    uses: dizi-izi-plan/dizi-izi-backend/.github/workflows/server_refresh.yml@ci-cd-pipelines
    secrets:
      SERVER_HOST: ${{ secrets.SERVER_HOST }}
      SERVER_USERNAME: ${{ secrets.SERVER_USERNAME }}
      SSH_KEY: ${{ secrets.SSH_KEY }}
      SSH_PASSPHRASE: ${{ secrets.SSH_PASSPHRASE }}

