name: Deploy to server
on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to server
    runs-on: ubuntu-22.04
    steps:

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd /root/infra
            touch .env
            
            sudo docker compose pull backend
            sudo docker compose stop
            sudo docker compose rm -f backend
            sudo docker image prune -f
            sudo docker volume prune -f
            sudo docker compose up -d