name: Docker image build
on:
  workflow_call:
  workflow_dispatch:

jobs:
  docker_image:
    name: Create and push docker image
    runs-on: ubuntu-22.04

    steps:

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Create Docker Image Name
        run: echo "IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/${GITHUB_REPOSITORY##*/}" >> $GITHUB_ENV

      - name: Set Commit SHA
        run: echo "COMMIT_SHA=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            $IMAGE_NAME:latest
            $IMAGE_NAME:$COMMIT_SHA
