name: Server update & restart
on:
  workflow_dispatch:
  workflow_call:
    secrets:
      SERVER_HOST:
        required: true
      SERVER_USERNAME:
        required: true
      SSH_KEY:
        required: true
      SSH_PASSPHRASE:
        required: true

jobs:
  deploy:
    name: Update & Restart Server
    runs-on: ubuntu-22.04
    steps:

      - name: Executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            cd /home/www/infra
            ./restart.sh all
